# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sample.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1361, 873)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(-140, -20, 1501, 951))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(1050, 730, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(240,167,98,219), stop:1 rgba(60, 98, 220, 226));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"background-color: qlineargradient(spread:pad,x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(212, 176, 178, 219), stop:1 rgba(105, 118, 132, 226));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(105,230,132,200);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(1190, 730, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(80, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton#pushButton_2:hover{\n"
"background-color: qlineargradient(spread:pad,x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40,67,98,219), stop:1 rgba(105, 118, 132, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#pushButton_2:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"color:rgba(255,110,90,200);\n"
"}\n"
"")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(450, 260, 571, 301))
        self.label.setText("")
        self.movie = QMovie("C:\\Users\harsh\Downloads\proxy.webp")
        self.label.setMovie(self.movie)
        self.movie.start()
        # self.label.setPixmap(QtGui.QPixmap("../../Downloads/proxy.webp"))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(0, -20, 431, 171))
        self.label_3.setText("")
        self.movie = QMovie("C:\\Users\harsh\Downloads\FavorablePerfectGermanspitz-size_restricted.gif")
        self.label_3.setMovie(self.movie)
        self.movie.start()
        # self.label_3.setPixmap(QtGui.QPixmap("../../Downloads/FavorablePerfectGermanspitz-size_restricted.gif"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(764, 80, 181, 101))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(370, 790, 781, 81))
        self.label_5.setText("")
        self.movie = QMovie("C:\\Users\harsh\Downloads\ee0139273e55e274bb86498b7836a350.gif")
        self.label_5.setMovie(self.movie)
        self.movie.start()
        # self.label_5.setPixmap(QtGui.QPixmap("../../Downloads/ee0139273e55e274bb86498b7836a350.gif"))
        self.label_5.setObjectName("label_5")
        self.date = QtWidgets.QTextBrowser(Form)
        self.date.setGeometry(QtCore.QRect(880, 60, 211, 51))
        self.date.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.date.setObjectName("date")
        self.time = QtWidgets.QTextBrowser(Form)
        self.time.setGeometry(QtCore.QRect(1090, 60, 211, 51))
        self.time.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.time.setObjectName("time")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.pushButton.setText(_translate("Form", "R U N"))
        self.pushButton_2.setText(_translate("Form", "E N D"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
