# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1141, 756)
        Form.setMouseTracking(True)
        Form.setAcceptDrops(True)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("QWidget#Form{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(220, 114, 160, 255), stop:1 rgba(240, 207, 211, 255));\n"
"}\n"
"")
        self.l1 = QtWidgets.QPushButton(Form)
        self.l1.setGeometry(QtCore.QRect(420, 450, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setStyleSheet("QPushButton#l1{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(240,167,98,219), stop:1 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton#l1:hover{\n"
"background-color: qlineargradient(spread:pad,x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(212, 226, 128, 200), stop:1 rgba(105, 118, 132, 226));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"\n"
"QPushButton#l1:pressed{\n"
"padding-left:4px;\n"
"padding-top:4px;\n"
"\n"
"}\n"
"")
        self.l1.setObjectName("l1")
        self.u1 = QtWidgets.QLineEdit(Form)
        self.u1.setGeometry(QtCore.QRect(390, 230, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.u1.setFont(font)
        self.u1.setStyleSheet("background-color:rgb(0,0,0,0);\n"
"border-radius:8px;\n"
"border:none;\n"
"border-bottom:3px solid rgb(105,118,132,255);\n"
"color: rgb(235, 235, 235);\n"
"padding-bottom:5px;\n"
"")
        self.u1.setObjectName("u1")
        self.p1 = QtWidgets.QLineEdit(Form)
        self.p1.setGeometry(QtCore.QRect(390, 330, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.p1.setFont(font)
        self.p1.setStyleSheet("background-color:rgb(0,0,0,0);\n"
"border:none;\n"
"border-radius:8px;\n"
"border-bottom:3px solid rgb(105,118,132,255);\n"
"color: rgb(235, 235, 235);\n"
"padding-bottom:5px;")
        self.p1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.p1.setClearButtonEnabled(True)
        self.p1.setObjectName("p1")
        self.signIn = QtWidgets.QPushButton(Form)
        self.signIn.setGeometry(QtCore.QRect(490, 590, 161, 31))
        self.signIn.setAutoFillBackground(False)
        self.signIn.setStyleSheet("QPushButton#signIn{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(80, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton#signIn:hover{\n"
"background-color: qlineargradient(spread:pad,x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40,67,98,219), stop:1 rgba(105, 118, 132, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#signIn:pressed{\n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"}\n"
"")
        self.signIn.setObjectName("signIn")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(490, 100, 141, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255,255,255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(480, 560, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgba(255, 255, 255,255);")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.l1.setText(_translate("Form", "L O G I N"))
        self.u1.setPlaceholderText(_translate("Form", "Enter the username"))
        self.p1.setPlaceholderText(_translate("Form", "Enter the password"))
        self.signIn.setText(_translate("Form", "Sigin In"))
        self.label_3.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\">kknkn</p></body></html>"))
        self.label_3.setText(_translate("Form", "Log In"))
        self.label_4.setText(_translate("Form", "New user ? Sign in"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
