# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SIGNup1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1134, 733)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 1141, 756))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color: qlineargradient(spread:pad, x1:0.495436, y1:0.023, x2:0.501, y2:0.994, stop:0 rgba(162, 169, 255, 255), stop:1 rgba(234, 222, 255, 255));\n"
"}")
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(500, 50, 121, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(216, 216, 216);")
        self.label_3.setObjectName("label_3")
        self.user = QtWidgets.QLineEdit(self.widget)
        self.user.setGeometry(QtCore.QRect(360, 150, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.user.setFont(font)
        self.user.setStyleSheet("background-color:rgb(0,0,0,0);\n"
"border-radius: 8px;\n"
"border:none;\n"
"border-bottom:1px solid rgb(105,118,132,255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:4px;\n"
"")
        self.user.setClearButtonEnabled(True)
        self.user.setObjectName("user")
        self.email = QtWidgets.QLineEdit(self.widget)
        self.email.setGeometry(QtCore.QRect(360, 330, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email.setFont(font)
        self.email.setStyleSheet("background-color:rgb(0,0,0,0);\n"
"border-radius: 8px;\n"
"border:none;\n"
"border-bottom:1px solid rgb(105,118,132,255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:5px;")
        self.email.setClearButtonEnabled(True)
        self.email.setObjectName("email")
        self.pnum = QtWidgets.QLineEdit(self.widget)
        self.pnum.setGeometry(QtCore.QRect(360, 420, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pnum.setFont(font)
        self.pnum.setStyleSheet("background-color:rgb(0,0,0,0);\n"
"border-radius: 8px;\n"
"border:none;\n"
"border-bottom:1px solid rgb(105,118,132,255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:5px;")
        self.pnum.setClearButtonEnabled(True)
        self.pnum.setObjectName("pnum")
        self.passw = QtWidgets.QLineEdit(self.widget)
        self.passw.setEnabled(True)
        self.passw.setGeometry(QtCore.QRect(360, 240, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.passw.setFont(font)
        self.passw.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.passw.setTabletTracking(False)
        self.passw.setAutoFillBackground(False)
        self.passw.setStyleSheet("background-color:rgb(0,0,0,0);\n"
"border-radius: 8px;\n"
"border:none;\n"
"border-bottom:1px solid rgb(105,118,132,255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:4px;\n"
"")
        self.passw.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.passw.setDragEnabled(False)
        self.passw.setReadOnly(False)
        self.passw.setClearButtonEnabled(True)
        self.passw.setObjectName("passw")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(420, 530, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(240,167,98,219), stop:1 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"background-color: qlineargradient(spread:pad,x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(212, 176, 178, 219), stop:1 rgba(105, 118, 132, 226));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(105,118,132,200);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(450, 620, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 660, 171, 31))
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(80, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,210);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton#pushButton_2:hover{\n"
"background-color: qlineargradient(spread:pad,x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40,67,98,219), stop:1 rgba(105, 118, 132, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#pushButton_2:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\">kknkn</p></body></html>"))
        self.label_3.setText(_translate("Form", "Sign in"))
        self.user.setPlaceholderText(_translate("Form", "Enter the username"))
        self.email.setPlaceholderText(_translate("Form", "Enter the email"))
        self.pnum.setPlaceholderText(_translate("Form", "Enter the phone number"))
        self.passw.setPlaceholderText(_translate("Form", "Enter the password"))
        self.pushButton.setText(_translate("Form", "S I G N   I N"))
        self.label_4.setText(_translate("Form", "Already Registered ? Login"))
        self.pushButton_2.setText(_translate("Form", "L O G I N   "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form1()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
